### ISSUE TITLE
nemo: Duplicate desktop item spawns over original

### ISSUE THREAD

**Issue by Mr-Dead** [linuxmint/mint21.1-beta#62]
Hello.  
With Auto-arrange disabled, selecting the "Copy to > Desktop" context menu command on a desktop item causes the item's duplicate to spawn over the original item.  Similar functions using keyboard shortcuts or cli do not exhibit such behavior.  Users expect the duplicate to spawn in a novel, unoccupied desktop location.

[copy_to-2022-12-11_06.40.15.webm](https://user-images.githubusercontent.com/2031616/206904121-3e13b122-2223-4fc8-9175-20a5a0866cbf.webm)

```

System:
  Kernel: 5.15.0-56-generic x86_64 bits: 64 compiler: gcc v: 11.3.0
    Desktop: Cinnamon 5.6.4 tk: GTK 3.24.33 wm: muffin vt: 7 dm: LightDM 1.30.0
    Distro: Linux Mint 21.1 Vera base: Ubuntu 22.04 jammy
Display: x11 server: X.Org v: 1.21.1.3 driver: X:
    loaded: modesetting,nvidia unloaded: fbdev,nouveau,vesa gpu: i915
    display-ID: :0 screens: 1
  Screen-1: 0 s-res: 1920x1080 s-dpi: 98 s-size: 499x280mm (19.6x11.0")
    s-diag: 572mm (22.5")
  Monitor-1: eDP-1 model: LG res: 1920x1080 hz: 60 dpi: 128
    size: 382x215mm (15.0x8.5") diag: 438mm (17.3") modes: 1920x1080
  OpenGL: renderer: Mesa Intel HD Graphics 4600 (HSW GT2)
    v: 4.6 Mesa 22.0.5 compat-v: 3.1 direct render: Yes

```
